// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrvupuqfkvvqvybgdjrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxydnVwdXFma3Z2cXZ5YmdkanJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NjIzNzksImV4cCI6MjA1MTQzODM3OX0.hzmdwYB-DA9rQgh7UnRkdDc54r4rR155gHruW_LGPmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);